---
name: "CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PYTHON_VERSION: "3.11"

jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Setup uv"
        uses: "astral-sh/setup-uv@v5"
        with:
          enable-cache: true
          python-version: "${{ matrix.python-version }}"

      - name: "Run tests"
        run: |
          uv sync --all-extras
          uv run coverage run -m pytest tests/
        env:
          VCRPY_ENCRYPTION_KEY: "${{ secrets.VCRPY_ENCRYPTION_KEY }}"

      - name: "Upload coverage data"
        uses: "actions/upload-artifact@v4"
        with:
          name: "coverage-data-${{ matrix.python-version }}"
          path: ".coverage.*"
          if-no-files-found: "ignore"
          include-hidden-files: true

  coverage:
    name: "Coverage report"
    runs-on: "ubuntu-latest"
    needs: "tests"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Setup uv"
        uses: "astral-sh/setup-uv@v5"
        with:
          enable-cache: true
          python-version: "${{ env.PYTHON_VERSION }}"

      - uses: "actions/download-artifact@v4"
        with:
          pattern: "coverage-data-*"
          merge-multiple: "true"

      - name: "Combine coverage"
        run: |
          uv sync --all-extras
          uv run coverage combine
          uv run coverage xml
          uv run coverage report

      - name: "Upload coverage reports to Codecov"
        uses: "codecov/codecov-action@v4"
        with:
          files: "coverage.xml"
        env:
          CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"

  checks:
    name: "${{ matrix.name }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        include:
          - name: "Code style checks"
            run_cmd: "uv run black --check --diff src/ tests/ noxfile.py && uv run isort --check --diff src/ tests/ noxfile.py && uv run ruff check --diff src/ tests/ noxfile.py && uv run interrogate src/ tests/ noxfile.py"
          - name: "Type checks"
            run_cmd: "uv run mypy src/ tests/ noxfile.py"
          - name: "Docs"
            run_cmd: "DISABLE_MKDOCS_2_WARNING=true uv run mkdocs build --strict"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Setup uv"
        uses: "astral-sh/setup-uv@v5"
        with:
          enable-cache: true
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: "Run checks"
        run: |
          uv sync --all-extras
          ${{ matrix.run_cmd }}
